version: '3.0'

services:
    ecommerce-api:
        build: .
        image: yixing/ecommerce-api
        container_name: ecommerce-api
        restart: on-failure:5
        network_mode: host
        ports:
            - "5018:5018"
        environment:
            ENV_DISABLE_DONATION_MSG: 1
            env: prod
        volumes:
            - ./assets:/code/assets
            - ./logs:/code/logs
            - ./database:/code/database
            - ./static2:/code/static2
        logging:
            driver: "json-file"
            options:
                max-size: "500m"
                max-file: "5"
e
