version: '3.0'

services:
    ecommerce-api:
        build: .
        image: yixing/ecommerce-api
        container_name: ecommerce-api
        restart: on-failure:5
        network_mode: host
        ports:
            - "5018:5018"
        env_file:
            - conf/prod.env
        volumes:
            - ./assets:/code/assets
            - ./logs:/code/logs
            - ./database:/code/database
        logging:
            driver: "json-file"
            options:
                max-size: "500m"
                max-file: "5"

